# Generated by Django 4.2.7 on 2023-12-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_record_address_remove_record_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.EmailField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='first_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='notes',
            field=models.CharField(default='', max_length=500),
        ),
    ]
